apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHU3dWo2NC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYTJGNWRHeDVibTVqTTBCbGMyaHBiVzlrTG1OdmJUcFRZVzUwYUc5emFERT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
